# Generated by Django 2.2.7 on 2019-11-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_text', models.CharField(max_length=200)),
                ('word_pos', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
